//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amortizacion
    {
        public int NumeroPago { get; set; }
        public Nullable<int> NumeroCredito { get; set; }
        public Nullable<int> PagoMensual { get; set; }
        public Nullable<int> CapitalAmortizado { get; set; }
        public Nullable<int> InteresPeriodo { get; set; }
        public Nullable<int> SaldoInsoluto { get; set; }
    
        public virtual Credito Credito { get; set; }
    }
}
